[build-system]
requires = ["setuptools>=68", "pybind11>=2.11", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bitlearn"
version = "1.1.5"
description = "ML algorithms with C++ backends"
authors = [{ name = "Vitthal Humbe", email = "vitthal.3454@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["numpy>=2.3", "tqdm", "scikit-learn"]
keywords = ["machine learning", "neural network", "linear regression", "C++"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.optional-dependencies]
benchmark = ["matplotlib", "pandas"]

[project.urls]
Homepage = "https://github.com/vitthalhumbe/bitlearn"
Repository = "https://github.com/vitthalhumbe/bitlearn"
Issues = "https://github.com/vitthalhumbe/bitlearn/issues"

[tool.setuptools.packages.find]
where = ["src"]